os: linux
dist: xenial
language: python
python:
- '3.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gcc
    - build-essential
    - python-dev
    - libnetfilter-queue-dev
install:
- pip install scapy==2.4.0
before_script:
- pip install -r requirements.txt
script:
- pytest
deploy:
  - provider: pypi
    user:
      secure: t1aUH/3MgRvar2M2OcJfsEB7kYvr9bxQgk/NSWORt1zrOC2tvRdmR+ukSmJAIDgH5I8uMb2NtOKEuZr+O6EXZBIQJsvH5acpxAPOmwJWucA8Nab5ELNyPhZK0lxGOh4WfQEMbZNjdt3DybwxuygR10twoc4fVJIhKd6JkWbsKWOx2bZZNPr6xfXtZvSOUCNGR9apQJTHNJ6lLRS4HtnamLOk+a+Uu4n1jsG2txpZNQQM9O/gndm5Sob8Ci9zfiHoSyd/yAtjEsxBj/WWc0hyjOQ5gBmg31bShjCXy3Gd4dhvPIPBo/KQHqfr5zyfpBeWB8Sj/DX1HblyuIUGHowJalx9HkctivpQwEcDuJsSsblSdXZTYx1PZIFteXAezLQY+wKd6D21wco+fHEGp21DvPNpmHg8kTW7aZCdSVbZRRUc7ChHRlewcy2Jvu8Umf4QoUfHJfNWhuwsS6VQh14cGyq9N+LvMQeZzK81KWSRb21l/swnafHP3cCzoxYp+feVhTkz+k6a5XX+3UzzD09JSCjBgtgx5FGLQOvJzW6KRQmqIgRthP4WqbBo4e7M7E9K1YTnc8vNTjQO0VWjHri83+sugWratLj0imYolJJeYnMhRAXnSyiw4drEKkj7R2HO6iVktfK3bZA+WLlBA1Y8qA7SS9O5Hyr4cbFU1AFEuXk=
    password:
      secure: VllS+XIgbxbvpHVn10PqHw1gn1TqM7HzycTgqUJRMNxX32AQFnuITPQWOEZXSN1RMAI7h3UhvDP2IwP6PEnxfGKqx3hgC/Yd4VAnypfNDr9lKitys7Nmp+JY8p4yWFjBGXjxj3IUstGpdG8CpSv1fKsCGWhf1H4JVA2ufKk9XSioe3cadcJSCuib/OVCZL/6dLzUsQsBnlS8Xq1WbxyBd3VsAW40IHQ9ChfMgXCPodTSNeEM26vxB7WLEYHvvfw/+/45NuMBu14Gc6YuUk1Pgg0lsUvCyfppR76LesUYpD5VB7XSC8wHay97hJ+NT2M4fUIDMcOHYjHSYT/eSNuHjyv0OaXqksmii6nwR3/av3ovUXInVIuqTGRK+7YVyqrblk3G/oRwBZgPLQRFh0xItufLSwS1nm6WHal7Lbsk9WbY2LJvGCY3940/Nh+skWm6jN/uMFipYCjl+1evtmth1sbmmrb4wnaabJsYjeuEV+ZfWx+3xIHOra7R57c2388vi8lvSenuw/CHAubgxj1b8UbHPRe5FHgAu2AjwsLFpIdt3F4R6oZM+kAJzjzq0w8kUuLotqk03bEl0/HoeQHapxTga9BsDz9lwXcn7guMikIheQ1iWK/8mt1lKuxrIsP0fbzGddQsaYupqzkQ4Fw3RnE8HwhNX+YeUK1b2V1TEes=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      tags: true
      branch: master
      repo: OWASP/SecureTea-Project
  - provider: releases
    api_key:
      secure: nVVfb5zysPx+HQS2Fkn1Pcmcu5Bp5L+s/KBJQ9peBR91ubKEQbAU+U5tw6qh8p729hE8c0Iq+MVzKdjhqVOoAJGfTC/XWxmZZMelUZ1QL6ZvDmbnVOuXrAh+1BbJqXqQ8K298dQbkjR+8F09aUOu2THIbUPz2b1FMXGbt1Kfc1ytvP8LwElJ4txAeUMo0Pj8ZRMOYd8DbLqSXPj6F89M8YK5Mk9jfgL2wojWolG3RO8v65Yd9HGr8tPKaMn7VrPmZYxaxqc64d1q83iOe2nVj3xpSUbJhlu1OTmmQQzEriUewHXRWEdoaDry7u3ExGwYbT+FP61uHE1jHBYcHz3neORK/gtPLVO5ueaoHdzJM9iPokTQUb6pGNV8DnDwZwWUZy8+llKQ6fx4hD0MTwjn7sx1o0Sd6qkbioWIkhJQI+vPqNzOkW1/fLLu/4PuAuveVVjw/uOHQfmzfUUb44eDg/SWhvXRKaPldhkmc97lVP+9abFQY+P3epWFMD+i2s1an4fu3H1Ww97w8Mhhq1J5KHIMxX7gN6hwcoWpoJ+sxZiia9YAf+u5GSNElZM+ka7zugM5GkFX8dSHLuCxWFvyt1nLaVJIhUG6eTWI//CghSgO9JRZ4YueyAgLj9MCVCVQxrM5OXHgZ+v6UzWTx6B+Ahs67BGm1wQYnU+2CGw2m1g=
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
      branch: master
      repo: OWASP/SecureTea-Project
env:
  global:
  - secure: xwsGmrtL88yRZgxzFZTrUe8GFnyZvenPAaFtAsDadkWsjsiUn7txv3K4RSBTYPzE8sd1JXavSGyIN3SMnsvc3o92+MAI0bStxVNA3lgmoOcIE/4Fp5iIoRWSXh4+JOgo28y3CnuaKp2/NJFN8k+N6vyGUXlw6XAzX1xcitQnSB3Jnz5SrEgHI+RTk9qtRXukxjVbMYlMg7tlUYHPXc7NzBK6QN+fVSydtHnAb9Qkb8z4FMqOMXp2sCAA4mSDRejaDiaKnj6Xv+u9tlRm0AqndOZRTZmM/Jc1IqWm1XemfRRVbUqyeJWmbbMAed0xZLd968tRVgXR6DEOAIcNqD5mElqdaGy9LEYZs3vbWmK7xTKH9Ua0+0Yh7HuMbjzoLgzyM7vBj28CYrZCFTbG74rVAR3OjoSVHpTp+e0LGbWSJQcRp3G1AZNKY6wl45kdVZ1hQKzC5jnI0jTHUvqvG/5CZ9D/grU6wyFk6DuMx5BHXrCErBbtsZHFQ4tsLchkg/A4ffxDxzpZbeyp1uUSJva26lXVQU+vDTvc4hV+DSC3irzXYyTicyI5a9tpOuBs3Tiohy8fU3WIJ6Q4H1KSeCYedMpXIcQdzwjAZoEZ3EgPyznJ0m3iPHijYMmWGdPXcVWua0BFCx0CflHYGTvSDiPxbB4BPC5G88apZQuPvZMOhiw=
  - secure: YlASKy23B3f7X3k9liCJm8a5SqBxXm+Mz+E05kg3iiBi0uz0pmUQgON/VSsLRf9/DiBfWafXn+Fpm5KKzSvZwMQKjIc0b1qQ9gMboJuYQDsxdufQyrFY6nrxvs397Ya9alcBK/nlCTtazXp8DrQSlLW3ff14sRZ25N4N91T0JMNuAFJNkz2p/azekXe77laj8Qp8ut4ouIOtVPY2ZnB1WKgQdqLNtgAnxtKl/LWr+6ysgK8DwagDQsH0zWl9K5WujvAdPlwtTvanETkTm7Gk2l2AQgu9J90v25qv0WeW+R95ElMy32IxPH/sxd+r2v8gcL2WI0ztPcUAnepKECYTmPPHRzlrqKx+YGAGOgCgCSWRFQe9XFZUCvXCireaqSy8U1sJ+RdogcMXYxZPRwaaM7ON3XoIOMrYIQF9y+7XducOE3pfBVw5KN4zdzL1AqWUawp9gMk5geVn2FjzgAW69GKeDyZ+ydrDNmG1Le0GjjGm+yCRy8oiM5nRYwrxV9RTsBMFYB2TSzRdLTopKzsIR7MetOOe16/tFrA6X58t/OhLabSNNC4n1u6Hp2DqRjkfp5aHaS8f3guXMJGJfMx09wI5b7GRIWmDGDJ2824Qm5zQy/eABKkRpLXKklLmP6wiJcI68GHpmDKNJyMz5zxx+F9CRcceo2NqOQTXBYvd0qI=
after_script:
- bash ./.teleNotify.sh
